server:
  port: ${PORT:8087}

spring:
  application:
    name: dispatch-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: dispatch-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.techstore.*"

app:
  kafka:
    topics:
      payment-completed: payment.completed
      order-dispatched: order.dispatched
      order-delivered: order.delivered

management:
  endpoints:
    web:
      exposure:
        include: health,info
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,OPTIONS"
