spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-training-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  kafka:
    topics:
      orders: orders
      notifications: notifications

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
