server:
  port: ${PORT:8082}

spring:
  application:
    name: product-service

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/productdb}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,OPTIONS"
