server:
  port: ${PORT:8084}

spring:
  application:
    name: inventory-service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/inventorydb}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.techstore.*"

app:
  kafka:
    topics:
      order-created: order.created
      inventory-reserved: inventory.reserved
      inventory-released: inventory.released
      inventory-failed: inventory.failed

management:
  endpoints:
    web:
      exposure:
        include: health,info
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,OPTIONS"
